services:
  rabbitmq-server:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - gestaocerta-private
networks:
  gestaocerta-private:
    external: true